notifications:
  email: false
addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libspatialindex-dev
language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pip -U
  - python get-poetry.py --preview -y
  - source $HOME/.poetry/env
  - poetry install -v
# command to run tests
script: pytest --runslow
