notifications:
  email: false
addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libspatialindex-dev
language: python
python:
  - "3.6"
# command to install dependencies
before_install:
- pip install poetry
install:
- poetry install -v
# command to run tests
script: pytest --runslow
